basic:
    name: Alvero.nl
    environments:
        production: 'https://www.alvero.nl'
        staging: 'https://alvero.opendev.be'
        development: ''
    breakpoints:
        - 480
        - 1024
        - 1200
    pages:
        - /
        - /producten/stoelen
        - '/producten/vergaderstoel-ode?v=697'
        - /cases/hubbz
        - /uitdagingen/lange-termijn
        - /over-alvero/daarom-alvero
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 5
    night_mode: ''
    retina_images: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: false
type: single-site
