basic:
    name: Alvero.nl
    environments:
        production: 'https://www.alvero.nl'
        staging: 'https://www.alvero.opendev.be/nl'
        development: ''
    breakpoints:
        - 480
        - 1024
        - 1200
    pages:
        - /
        - /producten/stoelen
        - '/producten/vergaderstoel-ode?v=697'
        - /cases/hubbz
        - /uitdagingen/lange-termijn
        - /over-alvero/daarom-alvero
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 40
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 15
    night_mode: false
    retina_images: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: '5'
        workers_nonproduction: '5'
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: true
type: single-site
